# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Test-Action-2
description: A simple test action 2 that prints "Hello, World!"

runs:
  using: composite
  steps:
    - name: Hello World
      shell: bash
      run: echo "Hello, World from Test-Action-2! This is a test action."
