# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Gitlint check
on:
  workflow_call:
    inputs:
      gitlint-file:
        description: "Path to the .gitlint file"
        required: false
        default: ".gitlint"
        type: string
      workflow-version:
        description: "Version of the workflow to use"
        required: false
        default: "main"
        type: string
jobs:
  lint-commits:
    name: check-commit-messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Checkout action
        uses: actions/checkout@v4.2.2
        with:
          # current repo name
          repository: eclipse-score/cicd-workflows
          ref: ${{ inputs.workflow-version }}
          path: ./cicd-workflows

      - name: Run Gitlint Action
        uses: ./cicd-workflows/.github/actions/gitlint
        with:
          pr-number: ${{ github.event.number }}
          base-branch: ${{ github.event.pull_request.base.ref }}
          gitlint-file: ${{ inputs['gitlint-file'] }}
